"use client";

import { useMemo, useState } from "react";

type Profile = { name:string; age:number; city:string; role:string; bio:string; interests:string[]; accent:string; audience:"Women"|"Men"; online?:boolean };

const profiles: Profile[] = [
  {name:"Aria",age:29,city:"Charlotte",role:"Creative director",bio:"Passport ready, ambitious, and happiest when a beautiful weekend turns into a great story.",interests:["Travel","Culture"],accent:"rose",audience:"Women",online:true},
  {name:"Maya",age:31,city:"Miami",role:"Founder",bio:"Building a beautiful life and looking for a confident partner who values intention and adventure.",interests:["Ambition","Wellness"],accent:"gold",audience:"Women"},
  {name:"Sofia",age:27,city:"Nashville",role:"Music producer",bio:"Live music, spontaneous escapes, and chemistry that feels effortless rather than rehearsed.",interests:["Culture","Travel"],accent:"plum",audience:"Women",online:true},
  {name:"Camille",age:33,city:"New York",role:"Art consultant",bio:"Gallery openings, quiet dinners, and someone who understands that taste is in the details.",interests:["Culture","Ambition"],accent:"wine",audience:"Women"},
  {name:"Nia",age:30,city:"Atlanta",role:"Brand strategist",bio:"Polished, warm, and ready for a connection that can keep up with a full and interesting life.",interests:["Ambition","Wellness"],accent:"emerald",audience:"Women"},
  {name:"Elena",age:28,city:"Austin",role:"Architect",bio:"Drawn to thoughtful people, beautiful spaces, and conversations that run later than planned.",interests:["Culture","Wellness"],accent:"copper",audience:"Women"},
  {name:"Grant",age:45,city:"Charlotte",role:"Real estate developer",bio:"Lake weekends, last-minute flights, and making sure the woman beside me feels appreciated.",interests:["Travel","Wellness"],accent:"gold",audience:"Men",online:true},
  {name:"Marcus",age:41,city:"Atlanta",role:"Technology founder",bio:"I value ambition, discretion, first-class travel, and thoughtful gestures that never feel ordinary.",interests:["Ambition","Travel"],accent:"indigo",audience:"Men"},
  {name:"Julian",age:48,city:"Miami",role:"Private investor",bio:"Hidden restaurants, ocean weekends, and creating memorable experiences with the right person.",interests:["Travel","Culture"],accent:"plum",audience:"Men"},
  {name:"Theo",age:39,city:"Nashville",role:"Entertainment executive",bio:"Confident, generous, and always planning the next concert weekend or luxury escape.",interests:["Culture","Travel"],accent:"wine",audience:"Men",online:true},
  {name:"Andre",age:44,city:"New York",role:"Finance executive",bio:"Great style, meaningful conversation, beautiful hotels, and surprises chosen with intention.",interests:["Ambition","Culture"],accent:"emerald",audience:"Men"},
  {name:"William",age:52,city:"Charleston",role:"Hospitality owner",bio:"Old-school manners, coastal getaways, and a soft spot for someone who truly appreciates the details.",interests:["Travel","Wellness"],accent:"copper",audience:"Men"},
];

const tiers=[
  {name:"Select",price:100,eyebrow:"Start intentionally",perks:["Curated discovery","Private profile","Member support"]},
  {name:"Black",price:1000,eyebrow:"Most popular",perks:["Priority discovery","Advanced preferences","Faster profile review"]},
  {name:"Icon",price:10000,eyebrow:"Invitation level",perks:["First discovery access","Concierge onboarding","Highest queue priority"]},
];
const filters=["All","Ambition","Travel","Culture","Wellness"];

export default function Home(){
  const [audience,setAudience]=useState<"Women"|"Men">("Women");
  const [filter,setFilter]=useState("All");
  const [saved,setSaved]=useState<string[]>([]);
  const [selected,setSelected]=useState<Profile|null>(null);
  const [toast,setToast]=useState("");
  const [menuOpen,setMenuOpen]=useState(false);
  const visibleProfiles=useMemo(()=>profiles.filter((p)=>p.audience===audience&&(filter==="All"||p.interests.includes(filter))),[audience,filter]);
  function goTo(id:string){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});setMenuOpen(false)}
  function toggleSave(profile:Profile){const isSaved=saved.includes(profile.name);setSaved((current)=>isSaved?current.filter((n)=>n!==profile.name):[...current,profile.name]);setToast(isSaved?`${profile.name} removed from your list.`:`${profile.name} saved to your matches.`);window.setTimeout(()=>setToast(""),2400)}

  return <main className="site-shell">
    <header className="topbar">
      <a className="wordmark" href="#top" aria-label="Sugar Papi home">Sugar <i>Papi</i><span aria-hidden="true">◆</span></a>
      <nav className="desktop-nav" aria-label="Primary navigation"><button onClick={()=>goTo("discover")}>Discover</button><button onClick={()=>goTo("how-it-works")}>How it works</button><button onClick={()=>goTo("memberships")}>Membership</button><button onClick={()=>goTo("matches")}>Saved <span>{saved.length}</span></button></nav>
      <div className="header-actions"><a className="text-link" href="/account">Sign in</a><a className="button button-light compact" href="/account">Join free</a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>☰</button></div>
    </header>
    {menuOpen&&<nav className="mobile-nav" aria-label="Mobile navigation"><button onClick={()=>goTo("discover")}>Discover</button><button onClick={()=>goTo("how-it-works")}>How it works</button><button onClick={()=>goTo("memberships")}>Membership</button><button onClick={()=>goTo("matches")}>Saved profiles ({saved.length})</button><a href="/account">Sign in or join</a></nav>}

    <section id="top" className="hero"><img src="/sugar-papi-hero.webp" alt="Two stylish adults enjoying a conversation at an elegant rooftop lounge"/><div className="hero-shade"/><div className="hero-content"><p className="kicker"><span/> Private by design · Curated by intention</p><h1>Meet someone who<br/>matches your <em>pace.</em></h1><p className="hero-copy">A more selective way for ambitious adults to meet—built around mutual interest, clear expectations, and meaningful chemistry.</p><div className="hero-actions"><a className="button button-light" href="/account">Create your profile <span>→</span></a><button className="button button-ghost" onClick={()=>goTo("discover")}>Browse the preview</button></div><p className="microcopy">Women join free · Men choose a membership · Cancel anytime</p></div><div className="hero-proof" aria-label="Member experience highlights"><div><b>Private</b><span>Protected profiles</span></div><div><b>Intentional</b><span>Mutual opt-in</span></div><div><b>Curated</b><span>Quality over volume</span></div></div></section>

    <section id="discover" className="content-section discover-section"><div className="section-heading"><div><p className="kicker"><span/> Discover</p><h2>Interesting people.<br/><em>Real possibilities.</em></h2></div><p>Preview a selection of profiles from the community. Photos and full details remain private until you join.</p></div><div className="discovery-controls"><div className="audience-tabs" role="tablist" aria-label="Profile groups"><button role="tab" aria-selected={audience==="Women"} onClick={()=>setAudience("Women")}>Women</button><button role="tab" aria-selected={audience==="Men"} onClick={()=>setAudience("Men")}>Men</button></div><div className="filter-row" aria-label="Filter profiles">{filters.map((item)=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div></div>
      <div className="profile-grid">{visibleProfiles.map((profile)=><article className="profile-card" key={profile.name}><button className={`profile-photo accent-${profile.accent}`} onClick={()=>setSelected(profile)} aria-label={`View ${profile.name}'s preview`}><span className="monogram">{profile.name[0]}</span><span className="photo-lock">Private photo</span>{profile.online&&<span className="online"><i/> Online now</span>}</button><div className="profile-body"><div className="profile-title"><button onClick={()=>setSelected(profile)}><h3>{profile.name}, {profile.age}</h3><p>{profile.role} · {profile.city}</p></button><button className={saved.includes(profile.name)?"heart saved":"heart"} onClick={()=>toggleSave(profile)} aria-label={`${saved.includes(profile.name)?"Remove":"Save"} ${profile.name}`}>{saved.includes(profile.name)?"♥":"♡"}</button></div><p>{profile.bio}</p><div className="interest-row">{profile.interests.map((interest)=><span key={interest}>{interest}</span>)}</div><button className="view-profile" onClick={()=>setSelected(profile)}>View preview <span>↗</span></button></div></article>)}</div><p className="sample-note">Preview profiles illustrate the intended member experience and do not represent actual users.</p>
    </section>

    <section id="how-it-works" className="process-section"><div className="process-intro"><p className="kicker"><span/> The Sugar Papi standard</p><h2>Less swiping.<br/><em>More substance.</em></h2><p>Every part of the experience is designed to make your time feel respected and your connections feel intentional.</p></div><div className="process-list"><article><span>01</span><div><h3>Create a thoughtful profile</h3><p>Tell us who you are, what you value, and the city where you want to connect.</p></div></article><article><span>02</span><div><h3>Discover with discretion</h3><p>Browse curated profiles while keeping private photos and personal details protected.</p></div></article><article><span>03</span><div><h3>Connect by mutual choice</h3><p>A conversation opens only after both members express interest—no cold messages.</p></div></article></div></section>

    <section id="memberships" className="content-section membership-section"><div className="section-heading membership-heading"><div><p className="kicker"><span/> Membership</p><h2>Choose your<br/><em>level of access.</em></h2></div><p>Women join free. Men select the membership that matches how quickly and personally they want to discover new profiles.</p></div><div className="tier-grid">{tiers.map((plan)=><article key={plan.name} className={plan.name==="Black"?"tier featured":"tier"}>{plan.name==="Black"&&<span className="popular">Most popular</span>}<p className="tier-name">{plan.name}</p><h3>${plan.price.toLocaleString()}<small>/month</small></h3><p className="tier-eyebrow">{plan.eyebrow}</p><ul>{plan.perks.map((perk)=><li key={perk}><span>✓</span>{perk}</li>)}</ul><a className={plan.name==="Black"?"button button-light full":"button button-outline full"} href={`/account?tier=${plan.name.toLowerCase()}`}>Choose {plan.name} <span>→</span></a></article>)}</div><p className="billing-note">Memberships renew monthly until canceled. Secure checkout is provided through Stripe after account sign-in.</p></section>

    <section id="matches" className="saved-section"><div><p className="kicker"><span/> Your shortlist</p><h2>{saved.length?`${saved.length} profile${saved.length===1?"":"s"} saved`:"Save the ones who catch your eye."}</h2><p>{saved.length?"Open a profile preview or continue discovering.":"Tap the heart on any profile to build a private shortlist."}</p></div>{saved.length?<div className="saved-list">{saved.map((name)=>{const profile=profiles.find((p)=>p.name===name)!;return <button key={name} onClick={()=>setSelected(profile)}><span>{profile.name[0]}</span><b>{profile.name}, {profile.age}</b><small>{profile.city}</small></button>})}</div>:<button className="button button-ghost" onClick={()=>goTo("discover")}>Browse profiles</button>}</section>

    <section className="closing-cta"><p className="kicker"><span/> Your invitation</p><h2>Raise your standards.<br/><em>Keep your expectations.</em></h2><p>More than a gym membership, less than a divorce.</p><a className="button button-light" href="/account">Join Sugar Papi <span>→</span></a></section>
    <footer><a className="wordmark" href="#top">Sugar <i>Papi</i><span>◆</span></a><p>Curated dating for ambitious adults.</p><div><button onClick={()=>goTo("how-it-works")}>How it works</button><button onClick={()=>goTo("memberships")}>Membership</button><a href="/account">Account</a></div><small>© 2026 Sugar Papi. Connections are mutual. Respect is required.</small></footer>

    {selected&&<div className="modal-backdrop" role="presentation" onClick={()=>setSelected(null)}><section className="profile-modal" role="dialog" aria-modal="true" aria-labelledby="profile-modal-title" onClick={(event)=>event.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close profile">×</button><div className={`modal-photo accent-${selected.accent}`}><span>{selected.name[0]}</span><small>Photo visible after joining</small></div><p className="kicker"><span/> Preview profile</p><h2 id="profile-modal-title">{selected.name}, {selected.age}</h2><p className="modal-meta">{selected.role} · {selected.city}</p><p>{selected.bio}</p><div className="interest-row">{selected.interests.map((interest)=><span key={interest}>{interest}</span>)}</div><div className="modal-actions"><button className={saved.includes(selected.name)?"button button-outline":"button button-ghost"} onClick={()=>toggleSave(selected)}>{saved.includes(selected.name)?"♥ Saved":"♡ Save profile"}</button><a className="button button-light" href={`/account?connect=${selected.name.toLowerCase()}`}>Join to connect <span>→</span></a></div></section></div>}
    {toast&&<div className="toast" role="status">✓ {toast}</div>}
  </main>
}
